# Generated by Django 4.1 on 2022-09-08 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0010_actor_movie_director_movie_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='slug',
        ),
    ]
