# Generated by Django 4.1 on 2022-09-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0014_dressingroom_actor_dressing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='slug',
        ),
    ]
