# Generated by Django 4.1 on 2022-09-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0016_movie_dressing_movie_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='dressing',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='dressing',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='slug',
        ),
        migrations.DeleteModel(
            name='DressingRoom',
        ),
    ]
