# Generated by Django 4.1 on 2022-09-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0017_remove_actor_dressing_remove_movie_dressing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
    ]
